version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: learnnest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: learnnest
    ports:
      - "3307:3306"

  backend:
    image: ninumaria/learnnest-backend:latest
    container_name: learnnest-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql